"use client";
import { useEffect, useRef, useState } from "react";

const GENERAL_NUMBER = "5548998429674";
const generalMessage = "Olá! Vim pelo site da Santos Corrêa e gostaria de conhecer melhor os serviços.";
const whatsappLink = (message = generalMessage, number = GENERAL_NUMBER) => `https://wa.me/${number}?text=${encodeURIComponent(message)}`;
type Service = { icon:string; title:string; description:string; how:string; includes:string[]; cta:string };

const services:Service[] = [
  {icon:"bi-journal-check",title:"Contabilidade",description:"Escrituração contábil, demonstrações, acompanhamento da situação da empresa e informações importantes para auxiliar na gestão e tomada de decisões.",how:"A equipe acompanha os registros e movimentações contábeis, organiza as informações necessárias e prepara demonstrações que auxiliam na compreensão da situação do negócio.",includes:["Escrituração contábil","Demonstrações contábeis","Organização das informações","Acompanhamento da situação da empresa","Informações de apoio à gestão"],cta:"Quero falar sobre minha contabilidade"},
  {icon:"bi-calculator",title:"Fiscal e Tributário",description:"Apuração de impostos, entrega de obrigações fiscais e acompanhamento tributário, buscando manter sua empresa regular e enquadrada de forma adequada.",how:"A Santos Corrêa acompanha obrigações fiscais e a apuração dos tributos aplicáveis conforme atividade e enquadramento da empresa.",includes:["Apuração de tributos","Obrigações fiscais","Acompanhamento de prazos","Análise do enquadramento","Orientação fiscal"],cta:"Quero orientação fiscal"},
  {icon:"bi-people",title:"Departamento Pessoal",description:"Folha de pagamento, admissões, férias, rescisões, encargos trabalhistas e demais rotinas relacionadas aos colaboradores.",how:"A equipe acompanha as principais rotinas relacionadas aos colaboradores da empresa.",includes:["Admissões","Folha de pagamento","Férias","Rescisões","Encargos e rotinas trabalhistas"],cta:"Preciso de suporte trabalhista"},
  {icon:"bi-buildings",title:"Abertura e Regularização",description:"Acompanhamento do processo de abertura, alteração e regularização, desde a definição das atividades até os registros necessários.",how:"A Santos Corrêa orienta o empresário nos procedimentos necessários para abertura, alteração ou regularização da empresa e seus cadastros.",includes:["Orientação inicial","Definição das atividades","Abertura","Alterações cadastrais","Regularizações","Orientação sobre registros"],cta:"Quero abrir ou regularizar minha empresa"},
  {icon:"bi-diagram-3",title:"Planejamento Tributário",description:"Análise da realidade da empresa para auxiliar na escolha e manutenção do regime tributário adequado, observando a legislação vigente.",how:"A situação da empresa é analisada considerando atividade, operação e realidade financeira para orientar decisões tributárias dentro da legislação vigente.",includes:["Análise do regime atual","Avaliação das características da empresa","Identificação de pontos de atenção","Orientação sobre enquadramento","Acompanhamento tributário"],cta:"Quero analisar minha empresa"},
  {icon:"bi-chat-square-text",title:"Consultoria Empresarial",description:"Orientação ao empresário em questões contábeis, fiscais, tributárias e trabalhistas.",how:"Acompanhamento próximo para dúvidas e decisões relacionadas às áreas contábil, fiscal, tributária e trabalhista.",includes:["Orientação contábil","Orientação fiscal","Questões tributárias","Questões trabalhistas","Apoio ao empresário"],cta:"Quero conversar com a equipe"}
];
const regimes = [
  {id:"mei",label:"MEI",title:"Está começando a empreender?",text:"Oferecemos suporte ao Microempreendedor Individual desde a formalização até o acompanhamento das obrigações da empresa. Auxiliamos com emissão de guias, declarações, regularizações, contratação de funcionário e também no momento em que o negócio cresce e precisa migrar para outro enquadramento.",highlight:"Seu negócio cresceu? Nós crescemos com você."},
  {id:"simples",label:"Simples Nacional",title:"Organização para continuar crescendo",text:"O Simples Nacional pode facilitar a tributação de micro e pequenas empresas, mas também exige acompanhamento para evitar irregularidades e pagamentos incorretos. A Santos Corrêa realiza a apuração dos tributos, acompanhamento do faturamento, obrigações fiscais, folha de pagamento e orientação tributária para empresas optantes pelo regime.",highlight:"Mais organização para você focar no crescimento da sua empresa."},
  {id:"presumido",label:"Lucro Presumido",title:"Acompanhamento contábil e tributário completo",text:"Para empresas enquadradas no Lucro Presumido, oferecemos acompanhamento contábil e tributário completo, com apuração dos impostos, cumprimento das obrigações acessórias e análise das operações da empresa. Nosso objetivo é proporcionar segurança nas informações e auxiliar o empresário na gestão tributária do negócio.",highlight:"Segurança nas informações para decisões mais tranquilas."},
  {id:"real",label:"Lucro Real",title:"Controle para operações mais estruturadas",text:"Empresas do Lucro Real exigem acompanhamento contábil e fiscal ainda mais detalhado. A Santos Corrêa está preparada para atender empresas enquadradas nesse regime, com controle e escrituração contábil, apuração tributária, obrigações acessórias e acompanhamento das operações que impactam a tributação.",highlight:"Contabilidade técnica, organizada e próxima da empresa."}
];
const journey = [["Está começando?","Ajudamos na abertura e organização do seu negócio."],["Já possui uma empresa?","Assumimos e acompanhamos toda a rotina contábil, fiscal e trabalhista."],["Sua empresa está crescendo?","Orientamos nas mudanças de enquadramento e nas novas necessidades contábeis e tributárias."],["Quer trocar de contabilidade?","Nossa equipe orienta sobre o processo de transferência e cuida dos procedimentos necessários para que a mudança seja realizada com segurança."]];
const teamMembers = [{name:"Rafaela Santos Corrêa",role:"Gerente Técnica",profession:"Contadora"},{name:"Vagner Corrêa",role:"Gerente Administrativo",profession:"Contador"}];

function Logo({jp=false}:{jp?:boolean}){const src=jp?"/logo/logo-jpcreative-fundo-transparente.jpeg":"/logo/Logo Corporativo Santos Correa Contabilidadlogo-santos-correa-fundo-transparente.png";return <img className={jp?"jp-logo":"brand-logo"} src={src} alt={jp?"JPCreative":"Santos Corrêa Contabilidade"}/>}
function Arrow(){return <i className="bi bi-arrow-up-right" aria-hidden="true"/>}
function ServiceModal({service,onClose}:{service:Service;onClose:()=>void}){const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();const onKey=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",onKey)}},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="service-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button ref={closeRef} className="modal-close" onClick={onClose} aria-label="Fechar detalhes"><i className="bi bi-x-lg"/></button><i className={`bi ${service.icon} modal-icon`} aria-hidden="true"/><p className="eyebrow">Serviço completo</p><h2 id="modal-title">{service.title}</h2><p className="modal-description">{service.description}</p><div className="modal-how"><h3>Como funciona</h3><p>{service.how}</p></div><ul>{service.includes.map(item=><li key={item}><i className="bi bi-check2"/>{item}</li>)}</ul><a className="button" href={whatsappLink(`Olá! Vim pelo site da Santos Corrêa e gostaria de saber mais sobre ${service.title}.`)} target="_blank" rel="noopener noreferrer"><i className="bi bi-whatsapp"/>{service.cta}<Arrow/></a></section></div>}

export default function Home(){
  const[menuOpen,setMenuOpen]=useState(false);const[scrolled,setScrolled]=useState(false);const[selectedService,setSelectedService]=useState<Service|null>(null);const[activeRegime,setActiveRegime]=useState(0);
  const footerRef=useRef<HTMLElement>(null);const whatsappRef=useRef<HTMLAnchorElement>(null);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add("is-visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));window.addEventListener("scroll",onScroll,{passive:true});return()=>{window.removeEventListener("scroll",onScroll);observer.disconnect()}},[]);
  useEffect(()=>{let frame=0;const reposition=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(!footerRef.current||!whatsappRef.current)return;const top=footerRef.current.getBoundingClientRect().top;const bottom=Math.max(20,window.innerHeight-top+20);whatsappRef.current.style.setProperty("--whatsapp-bottom",`${bottom}px`)})};reposition();window.addEventListener("scroll",reposition,{passive:true});window.addEventListener("resize",reposition);return()=>{cancelAnimationFrame(frame);window.removeEventListener("scroll",reposition);window.removeEventListener("resize",reposition)}},[]);
  const selectTab=(index:number)=>setActiveRegime((index+regimes.length)%regimes.length);
  return <>
    <header className={`header ${scrolled?"header--scrolled":""}`}><a href="#inicio" className="brand" aria-label="Santos Corrêa Contabilidade — início"><Logo/></a><button className="menu-toggle" aria-label={menuOpen?"Fechar menu":"Abrir menu"} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><span/><span/></button><nav className={menuOpen?"nav nav--open":"nav"} aria-label="Navegação principal"><a href="#inicio" onClick={()=>setMenuOpen(false)}>Início</a><a href="#servicos" onClick={()=>setMenuOpen(false)}>Serviços</a><a href="#regimes" onClick={()=>setMenuOpen(false)}>Regimes</a><a href="#sobre" onClick={()=>setMenuOpen(false)}>Quem somos</a><a href="#contato" onClick={()=>setMenuOpen(false)}>Contato</a><a className="button button--small" href={whatsappLink()} target="_blank" rel="noopener noreferrer">Falar com nossa equipe<Arrow/></a></nav></header>
    <main>
      <section className="hero" id="inicio"><div className="hero-grid" aria-hidden="true"/><div className="hero-copy"><p className="eyebrow hero-enter">Santos Corrêa Contabilidade</p><h1 className="hero-title hero-enter">Contabilidade que acompanha o crescimento da sua empresa.</h1><p className="hero-text hero-enter">Mais do que cuidar de números e obrigações, a Santos Corrêa Contabilidade trabalha lado a lado com empresários e empreendedores, oferecendo segurança, orientação e suporte para uma gestão mais tranquila e eficiente.</p><p className="hero-complement hero-enter">Atendemos empresas de diferentes portes e segmentos, com soluções personalizadas para cada fase do negócio.</p><div className="hero-actions hero-enter"><a className="button" href={whatsappLink()} target="_blank" rel="noopener noreferrer"><i className="bi bi-whatsapp"/>Falar com nossa equipe<Arrow/></a><a className="text-link" href="#servicos">Conhecer nossos serviços<i className="bi bi-arrow-down"/></a></div></div><aside className="hero-panel hero-enter" aria-label="Regimes tributários atendidos"><span className="panel-index">Da abertura à expansão</span><div className="orbit-mark"><span>SC</span></div><ul>{regimes.map(regime=><li key={regime.id}><i className="bi bi-check2"/>{regime.label}</li>)}</ul></aside><div className="hero-footer hero-enter"><span>Atendimento próximo</span><span>Gestão contábil completa</span><i className="bi bi-arrow-down-circle"/></div></section>
      <section className="positioning section"><div className="section-number reveal">SC</div><div className="positioning-copy reveal"><p className="eyebrow">Contabilidade para cada fase</p><h2>Segurança e orientação dos primeiros passos às operações mais estruturadas.</h2><p>Uma assessoria completa para organizar rotinas, apoiar decisões e acompanhar o desenvolvimento da sua empresa.</p></div><div className="concepts reveal"><span>Proximidade</span><span>Responsabilidade</span><span>Orientação</span><span>Segurança</span></div></section>
      <section className="services section" id="servicos"><div className="section-heading reveal"><div><p className="eyebrow">Assessoria completa</p><h2>Soluções completas para sua empresa</h2></div><p>Selecione um serviço para entender como a Santos Corrêa pode apoiar a rotina e as decisões do seu negócio.</p></div><div className="service-grid">{services.map((service,i)=><button className="service-card reveal" key={service.title} onClick={()=>setSelectedService(service)} style={{"--delay":`${i*55}ms`} as React.CSSProperties}><span className="card-number">0{i+1}</span><i className={`bi ${service.icon} card-icon`}/><h3>{service.title}</h3><p>{service.description}</p><span className="card-action">Ver detalhes <Arrow/></span></button>)}</div></section>
      <section className="regimes section" id="regimes"><div className="section-heading reveal"><div><p className="eyebrow">Enquadramento e acompanhamento</p><h2>Atendemos os principais regimes tributários</h2></div><p>Cada fase da empresa exige uma leitura diferente. Escolha um regime para conhecer nossa atuação.</p></div><div className="regime-tabs reveal" role="tablist" aria-label="Regimes tributários">{regimes.map((regime,index)=><button key={regime.id} role="tab" id={`tab-${regime.id}`} aria-controls={`panel-${regime.id}`} aria-selected={activeRegime===index} tabIndex={activeRegime===index?0:-1} onClick={()=>selectTab(index)} onKeyDown={e=>{if(e.key==="ArrowRight")selectTab(index+1);if(e.key==="ArrowLeft")selectTab(index-1)}}>{regime.label}</button>)}</div><article className="regime-panel" role="tabpanel" id={`panel-${regimes[activeRegime].id}`} aria-labelledby={`tab-${regimes[activeRegime].id}`} key={regimes[activeRegime].id}><span className="regime-index">0{activeRegime+1}</span><div><h3>{regimes[activeRegime].title}</h3><p>{regimes[activeRegime].text}</p><strong>{regimes[activeRegime].highlight}</strong></div></article></section>
      <section className="journey section"><div className="journey-heading reveal"><p className="eyebrow">Sua jornada com a Santos Corrêa</p><h2>Presença contábil em cada etapa do negócio.</h2></div><ol className="journey-line">{journey.map(([title,text],i)=><li className="reveal" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p>{i===0&&<a href={whatsappLink("Olá! Vim pelo site da Santos Corrêa e gostaria de orientação para abrir minha empresa.")} target="_blank" rel="noopener noreferrer">Quero abrir minha empresa <Arrow/></a>}{i===3&&<a href={whatsappLink("Olá! Vim pelo site da Santos Corrêa e gostaria de conversar sobre a troca da minha contabilidade.")} target="_blank" rel="noopener noreferrer">Quero trocar de contabilidade <Arrow/></a>}</li>)}</ol></section>
      <section className="institutional section" id="sobre"><div className="institutional-copy reveal"><p className="eyebrow">Quem somos</p><h2>Conhecimento técnico.<br/>Atendimento próximo.</h2><div className="institutional-text"><p>Somos um escritório contábil comprometido em oferecer atendimento próximo, responsável e eficiente.</p><p>Unimos conhecimento técnico e atendimento próximo para oferecer soluções nas áreas contábil, fiscal, tributária, trabalhista e empresarial.</p><p>Nosso propósito é construir relações de confiança e acompanhar nossos clientes em cada etapa do desenvolvimento de seus negócios.</p></div></div><div className="team-photo reveal"><span className="photo-index">Santos Corrêa · Imbituba / SC</span><img src="/equipe/rafaela-vagner-correa.jpeg" alt="Rafaela Santos Corrêa e Vagner Corrêa, da Santos Corrêa Contabilidade"/></div><div className="institutional-people reveal"><p className="people-label">À frente da Santos Corrêa</p><div className="team-people">{teamMembers.map(member=><article className="team-info" key={member.name}><span>{member.profession}</span><h3>{member.name}</h3><p>{member.role}</p></article>)}</div></div></section>
      <section className="final-cta section" id="contato"><div className="cta-copy reveal"><p className="eyebrow eyebrow--light">Converse com a nossa equipe</p><h2>Precisa de uma contabilidade para sua empresa?</h2><p>Se você está abrindo uma empresa, precisa regularizar seu negócio, deseja trocar de contador ou procura uma assessoria mais próxima, converse com a nossa equipe.</p><div className="regime-strip">MEI <span>•</span> Simples Nacional <span>•</span> Lucro Presumido <span>•</span> Lucro Real</div><a className="button button--light button--large" href={whatsappLink()} target="_blank" rel="noopener noreferrer"><i className="bi bi-whatsapp"/>Falar com a Santos Corrêa<Arrow/></a><small>Contabilidade próxima para empresas que querem crescer.</small></div><div className="contact-card reveal"><p className="contact-label">Canais de atendimento</p><a href={whatsappLink(generalMessage,"5548998429674")} target="_blank" rel="noopener noreferrer"><span>Rafaela Santos Corrêa · Contadora</span><strong>+55 48 99842-9674</strong></a><a href={whatsappLink(generalMessage,"5548998404585")} target="_blank" rel="noopener noreferrer"><span>Vagner Corrêa · Contador</span><strong>+55 48 99840-4585</strong></a><a href={whatsappLink(generalMessage,"5548998393480")} target="_blank" rel="noopener noreferrer"><span>Auxiliar contábil</span><strong>+55 48 99839-3480</strong></a><a href="mailto:rafaela@santoscontab.com"><span>E-mail Rafaela</span><strong>rafaela@santoscontab.com</strong></a><a href="mailto:vagner@santoscontab.com"><span>E-mail Vagner</span><strong>vagner@santoscontab.com</strong></a><a href="https://www.instagram.com/santoscorreacontabilidade/" target="_blank" rel="noopener noreferrer"><span><i className="bi bi-instagram"/> Instagram</span><strong>@santoscorreacontabilidade</strong></a><div className="contact-address"><span>Endereço</span><strong>João de Carvalho, s/n<br/>Bairro Campestre · Imbituba / SC</strong></div></div></section>
    </main>
    <footer ref={footerRef} className="footer"><div className="footer-main"><div><a href="#inicio" className="brand"><Logo/></a><p>Contabilidade próxima para empresas que querem crescer.</p></div><div><h3>Navegação</h3><a href="#servicos">Serviços</a><a href="#regimes">Regimes tributários</a><a href="#sobre">Quem somos</a><a href="#contato">Contato</a></div><div><h3>Principais serviços</h3>{services.slice(0,4).map(service=><button key={service.title} onClick={()=>setSelectedService(service)}>{service.title}</button>)}</div><div><h3>Fale conosco</h3><a href="mailto:rafaela@santoscontab.com">rafaela@santoscontab.com</a><a href="mailto:vagner@santoscontab.com">vagner@santoscontab.com</a><p>João de Carvalho, s/n<br/>Bairro Campestre<br/>Imbituba / SC</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Santos Corrêa Contabilidade.</span><a className="credit" href="https://jpcreative.com.br" target="_blank" rel="noopener noreferrer"><span>Desenvolvido por JPCreative</span><Logo jp/></a></div></footer>
    <a ref={whatsappRef} className="floating-whatsapp" href={whatsappLink()} target="_blank" rel="noopener noreferrer" aria-label="Conversar com a Santos Corrêa pelo WhatsApp"><i className="bi bi-whatsapp"/><span>Fale conosco</span></a>{selectedService&&<ServiceModal service={selectedService} onClose={()=>setSelectedService(null)}/>} 
  </>;
}
